CHANGELOG.rst,sha256=yu4VmFApc2BsHXAEJYL3_psGqFdFG--VqM3bUWctHh0,7719
django_auth_adfs/__init__.py,sha256=ZVKdiYbnbpHE-6frwbLEowykRUcpY6NQDOKeB0BFrks,136
django_auth_adfs/backend.py,sha256=lhUTx7ozbGmqbkZg6_aoKmSVcelui6mgzwL8nes7mPg,12348
django_auth_adfs/config.py,sha256=77CLqLaWsciUPUNPVCzci_5kdzG5wLLPlo_LZgGV5_Y,14347
django_auth_adfs/drf-urls.py,sha256=bBnN1WrgbHoiAs5hTGe-ovmVwwJ4D2xXpYtZVfE8l5U,221
django_auth_adfs/drf_urls.py,sha256=6mgMfGyrU9ftQimVHyQcck_nWT2WRuGov-AEe4OiFOc,352
django_auth_adfs/exceptions.py,sha256=9N6pxqlodau1teTJb38HNN9OvUY_jP0I_69dRMBbsK8,111
django_auth_adfs/middleware.py,sha256=st8Hx5pHWNcYUNWrCQht3QJqjw6RLQhWyxneTWal0Nw,2249
django_auth_adfs/rest_framework.py,sha256=spWIXpb8UtVDvZ0_W_sJB-5u0hwvLNUCqbAhHf9N0W4,1656
django_auth_adfs/signals.py,sha256=HGD79-dZNEwqVuINoqe6jB_8K1RfuK5Q288RGamTtEU,137
django_auth_adfs/templates/django_auth_adfs/login_failed.html,sha256=1NQ5aCjo7iTLSxy2IXJZbzBp5MaxpfsfQwQ_PDFvgr4,652
django_auth_adfs/urls.py,sha256=kkpOBa8fecr5jrNEhqApF90KOpFM8pPpUwq8GKUkuCY,514
django_auth_adfs/views.py,sha256=3-YdvywaPS6y_wEEU2sXBlMn2L6F2pZyIOZh114imdk,3868
django_auth_adfs-1.5.0.dist-info/LICENSE,sha256=n3ImkhGUnnJEu1sT51QKc_N22WdixSRcrfg9gj6nr3c,1296
django_auth_adfs-1.5.0.dist-info/WHEEL,sha256=SrtnPGVTMeYWttls9xnWA01eUhCZ3ufFdJUYb1J3r-U,83
django_auth_adfs-1.5.0.dist-info/METADATA,sha256=M7xWnbD1g7BIVqfQ2uoXkOAoAvlxv_Sztx59plm1hUA,6171
django_auth_adfs-1.5.0.dist-info/RECORD,,
